[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
ignore_missing_imports = True

[mypy-src.*]
ignore_errors = False

[mypy-middleware.*]
ignore_errors = False

[mypy-scripts.*]
ignore_errors = False

[mypy-tests.*]
ignore_errors = True

[mypy-conftest]
ignore_errors = True